[package]
name = "osmia-cli"
version = "0.2.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "osmia"
path = "src/main.rs"

[dependencies]
osmia = { git = "https://github.com/jkutkut/osmia" }
